name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 13
      run: echo "DEVELOPER_DIR=/Applications/Xcode_13.app/Contents/Developer" >> $GITHUB_ENV
    - name: Run Tests
      run: xcodebuild test -scheme 'ExampleSpringFadeTabs' -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' | xcpretty
